// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection. Against Supabase,
    // DIRECT_URL should be the port-5432 connection string; DATABASE_URL
    // (used by the app at runtime via the adapter in lib/db.ts) can be the
    // pooled pgbouncer one. Locally both point at the same dev database.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
